In [1]:
import tensorflow as tf 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import keras 
from keras.models import Sequential 
from keras.layers import Dense 
from sklearn.metrics import confusion_matrix 

In [2]:
data = pd.read_csv("C://Users//Sharvari//Downloads//heart.csv") 
data.head() 

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [3]:
data.describe() 

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [4]:
data.isnull().any() 

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [8]:
X = data.iloc[:,:13].values 
y = data["target"].values 

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size = 0.3 , random_state = 0 ) 
X_train
X_test
y_train
y_test

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,

In [18]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test) 
X_test

array([[-1.16453806,  0.65226323,  1.02564169, ...,  0.9790949 ,
        -0.73793656, -0.51108759],
       [ 0.38807624, -1.53312338,  0.05419507, ...,  0.9790949 ,
         1.20371671, -0.51108759],
       [ 0.94258134,  0.65226323, -0.91725155, ...,  0.9790949 ,
         1.20371671,  1.10322872],
       ...,
       [ 0.16627419,  0.65226323,  1.02564169, ..., -0.66111782,
         0.23289007, -2.12540389],
       [ 0.27717522, -1.53312338, -0.91725155, ...,  0.9790949 ,
        -0.73793656, -0.51108759],
       [-0.05552785,  0.65226323, -0.91725155, ..., -0.66111782,
         0.23289007,  1.10322872]])

In [20]:
classifier = Sequential() 
classifier.add(Dense(activation = "relu", input_dim = 13, 
					units = 8, kernel_initializer = "uniform")) 
classifier.add(Dense(activation = "relu", units = 14, 
					kernel_initializer = "uniform")) 
classifier.add(Dense(activation = "sigmoid", units = 1, 
					kernel_initializer = "uniform")) 
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy', 
				metrics = ['accuracy'] ) 
classifier

C:\Users\Sharvari\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<Sequential name=sequential_1, built=True>

In [15]:
classifier.fit(X_train , y_train , batch_size = 8 ,epochs = 100 ) 

Epoch 1/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 1s 742us/step - accuracy: 0.6050 - loss: 0.6910
Epoch 2/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.8576 - loss: 0.6023
Epoch 3/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.8449 - loss: 0.4259
Epoch 4/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step - accuracy: 0.8517 - loss: 0.3591
Epoch 5/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - accuracy: 0.8484 - loss: 0.3596
Epoch 6/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.8645 - loss: 0.3324
Epoch 7/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.8740 - loss: 0.3236
Epoch 8/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.8774 - loss: 0.3243
Epoch 9/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.8777 - loss: 0.3085
Epoch 10/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - accuracy: 0.8472 - loss: 0.3330
Epoch 11/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.8611 - loss: 0.3353
Epoch 12/100
90/90 ━━━━━━━━━━━━━━━━━━━━ 0

In [16]:
y_pred = classifier.predict(X_test) 
y_pred = (y_pred > 0.5) 

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [17]:
cm = confusion_matrix(y_test,y_pred) 
cm 

array([[139,   6],
       [  8, 155]], dtype=int64)

In [21]:
accuracy = (cm[0][0]+cm[1][1])/(cm[0][1] + cm[1][0] +cm[0][0] +cm[1][1]) 
print(accuracy*100) 

95.45454545454545
